kind: Deployment
apiVersion: apps/v1
metadata:
  name: shopdeploy
  namespace: shoping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
      name: shoppod
    spec:
      containers:
        - name: user
          image: anubhav730/app1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1234
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

        - name: cart
          image: anubhav730/app2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1235
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

        - name: items
          image: anubhav730/app3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1236
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

        - name: frontend
          image: anubhav730/app4:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4200
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

---

kind: Service
apiVersion: v1
metadata:
  name: shopsvc
  namespace: shoping-app
spec:
  selector:
    app: shop
  ports:
    - protocol: "TCP"
      port: 4200
      targetPort: 4200
  type: NodePort

