version: '3.8'

services:
  app1:
    build:
      context: ./Users
      dockerfile: Dockerfile
    image: anubhav730/app1:latest
    container_name: User
    ports:
      - "1234:1234"
  app2:
    build:
      context: ./ShopCartH2
      dockerfile: Dockerfile
    image: anubhav730/app2:latest
    container_name: Cart
    ports:
      - "1235:1235"
  app3:
    build:
      context: ./ShopItemH2
      dockerfile: Dockerfile
    image: anubhav730/app3:latest
    container_name: Item
    ports:
      - "1236:1236"
  app4:
    build:
      context: ./Shopping
      dockerfile: Dockerfile
    image: anubhav730/app4:latest
    container_name: Frontend
    ports:
      - "4200:4200"

